export const COLOMBIA_CITIES = [
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Bucaramanga",
  "Cúcuta",
  "Pereira",
  "Manizales",
  "Armenia",
  "Ibagué",
  "Neiva",
  "Villavicencio",
  "Pasto",
  "Santa Marta",
  "Montería",
  "Valledupar",
  "Popayán",
  "Sincelejo",
  "Tunja",
  "Riohacha",
  "Quibdó",
  "Florencia",
  "Yopal",
  "Arauca",
  "Leticia",
  "San Andrés",
] as const;

export type ColombiaCity = (typeof COLOMBIA_CITIES)[number];
